bytebase/bytebase.com

README.md
Fixed the render.com link in the README.md
=> doc: fixed the render.com link

common/plan.ts, components/TheHeader.vue, pages/pricing/index.vue
=> docs: update pricing style, wording change and add pricing link to the non-index page header

common/plan.ts, components/QuestinIcon.vue, pages/pricing/index.vue
=> feat: update pricing page

common/plan.ts, pages/index.vue, pages/pricing/index.vue
=> doc: update pricing matrix and feature wording

common/plan.ts
=> fix grammar error

common/plan.ts, pages/pricing/index.vue
Need to reduce the button padding as the text is too long.
=> feat: update trial price

.vscode/settings.json, package.json, yarn.lock
use the same vscode setting as the main bytebase app https://github.com/bytebase/bytebase/blob/main/.vscode/settings.json
=> chore: add vscode settings to unify format

package.json, yarn.lock
=> fix: `lodash` version

docs/document-guide.md
=> fix: document guide order

docs/error-code.md, docs/faq.md
> This is an example PR about "how to add a new document?".
⚠️ Attension points:
* You don't need to change any code file;
* Follow the `./docs/` folder structure, figure out the `order` value;
* There shouldn't be any duplicate `order` values, if you put a new file between others you need to change the other file `order`.
=> feat: add `Error Code` document

components/DocsSidebar.vue, layouts/content.vue, types/docs.d.ts
Try to fix:
* toggle document folder;
* position sidebar when first enter to page;
* font space problem;
(But I cannot recover them in dev or prod.)
=> chore: update sidebar props

common/const.ts, components/DocsSidebar.vue, layouts/content.vue, pages/docs/_category/_document.vue
Fix last PR error with document list.
=> fix: sidebar documentList data

app.html
https://clearbit.com/resources/tools/visitor-report#install
=> docs: add clearbit tracking

components/ActionSection.vue, components/TheHeader.vue, layouts/content.vue, layouts/default.vue, layouts/integration.vue, layouts/main.vue, layouts/usecase.vue, pages/index.vue
=> feat: sticky header

CODEOWNERS
Since I am actively working on this area with the rest of the team.
=> Add tianzhou as the OWNER

components/TheFooter.vue, components/TheHeader.vue, layouts/default.vue, layouts/integration.vue, layouts/usecase.vue
Using grid layout instead of sticky to fix page error position with hash.
=> feat: use grid layout instead of sticky

pages/about.vue, pages/brand.vue, pages/changelog/_slug/index.vue, pages/compare/_slug/index.vue, pages/database-feature/_slug/index.vue, pages/database-glossary/_slug/index.vue, pages/database-glossary/index.vue, pages/database-review-guide/index.vue, pages/database/clickhouse.vue, pages/database/mysql.vue, pages/database/postgres.vue, pages/database/snowflake.vue, pages/database/tidb.vue, pages/index.vue, pages/integration/dingtalk.vue, pages/integration/discord.vue, pages/integration/feishu.vue, pages/integration/slack.vue, pages/integration/teams.vue, pages/integration/wecom.vue, pages/jobs.vue, pages/pricing/index.vue, pages/privacy.vue, pages/refund/index.vue, pages/software/_slug/index.vue, pages/usecase/dba.vue, pages/usecase/developer.vue, pages/usecase/techlead.vue, pages/vcs/_slug/index.vue, pages/webhook/_slug/index.vue
Update all page head attribute with metadata for SEO.
=> feat: update pages head attribute

pages/index.vue
Fix action section max width in mobile view
=> fix: action section style

components/DocumentViewer.vue
=> feat: copy button for docs pages

components/DocumentViewer.vue, components/SearchDocsDialog.vue, components/SubscribeSection.vue, layouts/content.vue
=> feat: add subscribe section in docs

app.html, components/DocsSidebar.vue, layouts/content.vue, pages/docs/index.vue
Update data initialization logic to avoid loading data for document pages.
=> feat: update docs pages data initial

common/storage.ts, components/DocumentViewer.vue, components/SubscribeSection.vue
=> feat: subscribtion popup in docs pages

components/SubscribeSection.vue, components/TheFooter.vue, layouts/blog.vue, pages/blog/_slug/index.vue, pages/blog/index.vue
---
This PR should be merged after @adela-bytebase has updated 5 articles with featured tag. The first featured article will be at the primary position, and the other 4 articles will be placed at the bottom of it.
=> feat: redesign blog main page

pages/blog/index.vue
* align center for latest feature blog title block;
=> chore: update `/blog` page style

components/TheFooter.vue, pages/blog/_slug/index.vue, pages/blog/index.vue, pages/changelog/_slug/index.vue, pages/changelog/index.vue, pages/database-glossary/_slug/index.vue, pages/database-glossary/index.vue, pages/index.vue
=> feat: add subscribtion section to footer

components/TeamSection.vue
=> add candy to team page

pages/jobs.vue
=> docs: remove backend and frontend full-time position

components/DocsSidebar.vue
=> chore: root section foldable

assets/svg/earth.svg, components/TheFooter.vue, nuxt.config.js, pages/blog/index.vue
=> feat: add locale selector into footer

common/utils.ts, layouts/content.vue
=> chore: add `ctrl+K` symbol in search block

layouts/content.vue, pages/index.vue
Use the locale from browser default.
=> chore: set locale from browser in `/` index page

common/storage.ts, pages/index.vue, store/index.ts
Use store to prevent always redirect locale.
=> fix: locale redirect

pages/index.vue
We shouldn't auto-redirect `/zh` to `/` in english env.
=> chore: update redirect policy

pnpm-lock.yaml
=> chore: update `pnpm-lock.yaml` file

docs/en/reference/cli.md, layouts/content.vue
* Use `prettier` format markdown file.
* Add `cli` entry to docs header.
=> chore: add `cli` entry to docs header

common/const.ts, components/DocsSidebar.vue, components/DocumentViewer.vue, docs/en/_layout.md, docs/en/cli/_layout.md, docs/en/cli/overview.md, layouts/content.vue, types/docs.d.ts
Now the sidebar content is the same as the TOC of cli doc. We can change it in `/docs/en/cli/_layout.md`.
=> feat: sub-sidebar for `/docs/cli`

components/AlgoliaSearchDialog.vue, components/DocsSidebar.vue, components/DocumentViewer.vue, layouts/content.vue, nuxt.config.js, pages/docs/_category/_document.vue, pages/docs/_category/_subcategory/_document.vue, pages/docs/_slug.vue, types/docs.d.ts
* Remove subscribe popup in docs;
* Update search result style;
* Add `tags` field from doc path for searching;
=> chore: update docs style

locales/en.json, locales/zh.json, pages/index.vue
=> chore: update main page translation

content/docs/en/_layout.md, content/docs/en/settings/customize-workspace.md
update _layout and customize-workspace
=> docs: update _layout and customize-workspace

pages/blog/_slug/index.vue, pages/blog/index.vue, pages/changelog/_slug/index.vue
* add `readingTime` in blog page;
* fix mobile padding styles;
=> chore: update style

layouts/blog.vue, pages/blog/_slug/index.vue, pages/blog/index.vue, pages/changelog/_slug/index.vue, pages/changelog/index.vue, pages/database-glossary/_slug/index.vue
* hidden banner and submenus in mobile view for blog page;
* update prose size in mobile view;
=> chore: update blog page style in mobile view

app.html
Decided to not move forward with hubspot at this point.
=> chore: remove hubspot tracking code

components/DocumentViewer.vue, layouts/content.vue, tsconfig.json
=> chore: update search box style

nuxt.config.js, pages/blog/_slug/index.vue, pages/changelog/_slug/index.vue
Add domain prefix for header meta image so that it can show the featured image when sharing in twitter.
=> chore: update meta image

common/plan.ts, locales/en.json, locales/zh.json, pages/pricing/index.vue
=> chore: update wording for free trial

locales/zh.json
from ”迁移“ to ”变更“
related PR [#1521 in bytebase/bytebase](https://github.com/bytebase/bytebase/pull/1521)
=> chore(i18n): re-translate migration in zh-CN

components/DocumentViewer.vue, components/IncludeBlock.vue, pnpm-lock.yaml
* fix `IncludeBlock` component for docs;
* update `pnpm-lock.yaml` file;
=> fix: docs include block component

content/docs/en/features/sql-advisor/overview.md
pic is 404, should be .webp instead of .png
=> chore: fix picture format

locales/en.json
Fixing the problem shown below.
=> fix(i18n): wrong resource key

common/plan.ts, locales/en.json, locales/zh.json, pages/pricing/index.vue
- Team plan: from $29 to $79
- Enterprise plan: add "Start from" prefix
=> chore: update price for team and enterprise plan

pages/pricing/index.vue
|before|after|
|-|-|
|<img width="977" alt="image" src="https://user-images.githubusercontent.com/24653555/175015682-1533bb00-8da4-4cca-9699-274d4eb74e40.png">|<img width="1010" alt="image" src="https://user-images.githubusercontent.com/24653555/175015606-5d33e897-8a74-4daf-94e2-e772b8a88aff.png">|
=> fix: feature tooltip in pricing page

pages/pricing/index.vue
=> docs: use small font for “start from”

layouts/blog.vue, layouts/content.vue, layouts/default.vue, layouts/integration.vue, layouts/usecase.vue, locales/en.json, locales/zh.json, pages/pricing/index.vue
- Optimize the pricing
- Fix the segment init error in SSR (the window will be undefined in SSR)
=> chore: optimize pricing and fix segment error in SSR

content/docs/en/install/build-from-source.md, content/docs/en/install/install-with-docker.md
=> docs: update to 1.2.0

content/docs/en/get-started/deploy-in-5-seconds.md
Follow up of https://github.com/bytebase/bytebase/pull/1626
=> docs: pass version string when running the quick start docker compose

content/changelog/bytebase-1-2-0.md
fixing a typo and clarifying the rules for schema review.
=> docs: modify 1.2.0 changelog

components/DocumentViewer.vue, components/IncludeBlock.vue, content/docs/en/document-write-guide.md, layouts/blog.vue, layouts/default.vue, layouts/integration.vue, layouts/usecase.vue
=> chore: make markdown style scope

components/ActionSection.vue, components/Header.vue, components/SubscribeSection.vue, pages/pricing/index.vue, plugin/cookie.ts, plugin/segment.ts
The segment client could be null for the first time as it is initialized asynchronously.
=> fix: segment initialization

common/teammate.ts, components/PastCompanyBar.vue, components/TeamSection.vue, locales/en.json, locales/zh.json
=> docs: add a separate founder section

components/TeamSection.vue, pages/pricing/index.vue
=> docs: add pastcompany section to the pricing page

components/TeamSection.vue, pages/blog/_slug/index.vue, pages/blog/index.vue, pages/changelog/_slug/index.vue, pages/changelog/index.vue
If the author is not found in the teammate list, then we only display the name and not the avatar.
=> fix: blog/changelog author avatar

.gitignore, common/schemaSystem.ts, components/InputWithTemplate/InputWithTemplate.vue, components/SchemaSystem/SchemaConfigurationPage.vue, components/SchemaSystem/SchemaRuleConfig.vue, components/SchemaSystem/SchemaRuleLevelBadge.vue, components/SchemaSystem/SchemaSystemPreview.vue, locales/en.json, locales/zh.json, nuxt.config.js, package.json, pages/database-review-guide/index.vue, pnpm-lock.yaml, scripts/get_schema_review_rules.sh, tsconfig.json, types/yaml.d.ts
- Using yaml file for schema review configuration.
- Update the localization.
=> chore: extract yaml file for schema review configuration

components/ActionSection.vue, components/Header.vue, layouts/content.vue, pages/pricing/index.vue
=> fix: deploy-in-5-seconds url

content/docs/en/api/sql-advise.md
=> docs: add stage info for SQL advise API

.gitignore, README.md, components/SchemaSystem/SchemaConfigurationPage.vue, components/SchemaSystem/SchemaRuleConfig.vue, components/SchemaSystem/SchemaRuleLevelBadge.vue, components/SchemaSystem/SchemaSystemPreview.vue, locales/en.json, locales/zh.json, nuxt.config.js, package.json, scripts/fetch_sql_review_file.sh, scripts/get_schema_review_rules.sh, scripts/get_sql_review_configuration.sh
Pending https://github.com/bytebase/bytebase/pull/1801
=> chore: use localization files in console for sql review

content/blog/database-version-control-state-based-vs-migration-based.md
If I understand it correctly, I think this is a typo.
=> docs: fix typo in heading

content/docs/en/_layout.md, content/docs/en/get-started/quick-start.md
1. Move Get Started above Concepts
2. Title "Quick Start (5 mins Test)" -> 5 Mins Quick Start
=> docs: change layout

components/DocumentViewer.vue, components/Toc.vue, content/docs/en/get-started/install/build-from-source-code.md, content/docs/en/get-started/install/installation-script.md, content/docs/en/get-started/quick-start.md
* fix toc scrollbar in docs;
* format some doc files.
=> chore: update toc styles in doc

components/Header.vue
=> docs: use “Live demo” instead of “Demo”

components/DocsSidebar.vue, content/docs/en/_layout.md
=> chore: render separator in docs sidebar

components/Toc.vue
=> style: hide scroll bar of blog toc

scripts/fetch_sql_review_file.sh
Use the `VERSION` file to align the SQL Review configuration
=> chore: update the resource url for sql review

layouts/blog.vue
brand doesn't provide problem solving value for visitors.
=> docs: remove brand from the blog menu bar

components/DocumentViewer.vue
=> fix: copy button style in include-block

pages/index.vue
According to ahrefs suggestion
=> docs: add more meta content

locales/en.json, locales/zh.json, nuxt.config.js, pages/index.vue
* Title changed to "Database DevOps"
* Put "Developer" first
=> docs: tweak slogan

components/DocLinkBlock.vue
https://user-images.githubusercontent.com/56376387/182280402-e5c05b5c-f549-45c2-b645-cdfecb63014f.mp4
https://user-images.githubusercontent.com/56376387/182280421-52e60867-383e-4e0f-942b-e834531c00a7.mp4
=> fix: doc sidebar not changing on content changes

content/docs/en/get-started/quick-start.md
=> docs: fix typo and format

components/SubscribeSection.vue
=> chore: increase the newsletter subscription email field width

components/SchemaSystem/SchemaConfigurationPage.vue, components/SchemaSystem/SchemaSystemPreview.vue, content/docs/en/sql-review/review-rules/overview.md, content/docs/en/sql-review/review-rules/supported-rules.md, content/docs/en/sql-review/rules.md
Add the anchor for each rule, thus we can easily link to the docs by rule type.
Add comments in the YAML file: add docs and the markplace URL.
=> chore: update SQL review docs and the YAML file

components/ActionSection.vue, components/Icons/Calendar.vue, locales/en.json, locales/zh.json, pages/demo/index.vue
| Before | After |
| :---: | :---: |
| ![CleanShot 2022-08-09 at 15 09 51](https://user-images.githubusercontent.com/56376387/183586688-ba6ef595-7e25-4c34-b705-2de65f1b8b37.png) | ![CleanShot 2022-08-09 at 15 08 27](https://user-images.githubusercontent.com/56376387/183586495-47e27cc6-0b4f-4b0f-bc46-f731ca7afbfb.png) |
| Before Submit | After Submit |
| :---: | :---: |
| ![CleanShot 2022-08-09 at 15 12 57](https://user-images.githubusercontent.com/56376387/183587308-b1a0c385-27f4-4788-b988-ccc0ed3a0561.png) | ![CleanShot 2022-08-09 at 15 12 41](https://user-images.githubusercontent.com/56376387/183587233-82b15905-e3e9-4d01-9ad1-b95ce44bf1aa.png) |
=> feat: add demo request entry

CODEOWNERS
Guess @ecmadao @boojack should be enough. I can still do code review if needed, just want to spare myself from the default reviewer list.
=> chore: retire myself as the frontend code reviewer

components/ActionSectionBottom.vue, components/Footer.vue, locales/en.json, locales/zh.json, pages/database-feature/_slug/index.vue, pages/index.vue, pages/vcs/_slug/index.vue, pages/webhook/_slug/index.vue
Replace newsletter subscription with CTA
=> chore: better CTA

components/BookDemoSection.vue, locales/en.json, locales/zh.json, pages/demo/index.vue, pages/index.vue
=> feat: add "Book a Demo" on the homepage

content/blog/30saas-services-behind-startup.md, content/blog/database-review-2021-andy-pavlo-chinese.md, content/blog/database-review-2021-bytebase-chinese.md, content/changelog/bytebase-1-0-2.md, content/docs/en/get-started/configure-workspace/register-accounts.md
* Github -> GitHub
* Gitlab -> GitLab
=> chore: fix brand typos

content/docs/en/get-started/install/deploy-to-kubernetes.md, content/docs/en/get-started/install/deploy-with-docker.md
kubernetes: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request
docker: https://docs.docker.com/engine/reference/run/#healthcheck
=> docs: add health check option in kubernetes and docker

content/blog/how-to-cross-compile-with-cgo-use-goreleaser-and-github-action.md
=> chore: fix GitHub Actions name

components/ActionSectionBottom.vue, components/BookDemoSection.vue, locales/en.json, locales/zh.json, pages/index.vue
Combine logo cloud with CT and use a bold style
Followup PRs will improve the other area to match the style
=> docs: update CTA section

components/ActionSectionBottom.vue, components/SubscribeSection.vue, layouts/blog.vue, locales/en.json, locales/zh.json, pages/blog/index.vue
Make the style more consistent and bold
=> chore: improve blog index layout and style

components/BookDemoSection.vue, components/SubscribeSection.vue
=> fix: fix mobile view subscribe and demo

components/DatabaseBar.vue, components/MainBanner.vue, locales/en.json, locales/zh.json, pages/changelog/index.vue, pages/index.vue, pages/pricing/index.vue, pages/techstack.vue
* Unify color palette to converge on indigo
* Reduce text
* Enlarge text and illustration to make it look bold
=> docs: simplify 1st screen

pages/demo/index.vue
=> chore: enlarge the demo buttom to avoid wrapping

components/BookDemoSection.vue
=> docs: optimize the request demo button

content/blog/database-cicd-best-practice-with-github.md
=> chore: replace devops with cicd

content/docs/en/vcs-integration/name-and-organize-schema-files.md
https://github.com/bytebase/bytebase/pull/2417
=> docs: update the file path template part of VCS integration

locales/en.json
Experiment with more explicit word.
=> chore: change slogan

locales/en.json
=> chore: capitalized the action word

components/DocumentViewer.vue, components/Toc.vue
=> style: make ToC fit to window height

components/Toc.vue
https://user-images.githubusercontent.com/56376387/190551425-d507b115-1cb0-42f7-9d32-6e89430b6c5b.mp4
https://user-images.githubusercontent.com/56376387/190551430-668b585a-dfe5-404c-b857-f740bb7ba79f.mp4
=> fix: ToC not changing when visit page by anchor link

content/docs/en/sql-review/review-rules/supported-rules.md
=> chore: remove unnecessary escaping

content/docs/en/_layout.md, content/docs/en/disaster-recovery/backup-restore-database/cloud-backup.md, content/docs/en/disaster-recovery/backup-restore-database/overview.md
=> feat: add docs for backup to the cloud

content/docs/en/reference/command-line.md
=> docs: fix the command-line doc

nuxt.config.js
=> chore: resolve port conflicts

common/sqlReview.ts, components/BBCheckbox.vue, components/SchemaSystem/SchemaConfigurationPage.vue, components/SchemaSystem/SchemaRuleConfig.vue, components/SchemaSystem/SchemaSystemPreview.vue
Note:
The new rules will only take effect after we release the new version for Bytebase and bytebase.com
=> chore: support sql review rules

locales/en.json, locales/zh.json, pages/pricing/index.vue
=> docs: update slogan in pricing

components/Footer.vue, components/MainBanner.vue
=> docs: add DevJoy link

locales/en.json, locales/zh.json, nuxt.config.js, pages/index.vue
Make the frontend look more alive. Point to the latest changelog page
=> docs: tweak chinese hero section wording and add what’s new

content/docs/en/concepts/roles-and-permissions.md
* Clarify only workspace owner can change any project's role
* Center checkmark of the permission table
=> docs: update roles and permission

locales/en.json, locales/zh.json, pages/index.vue
=> docs: add detail text for Database DevOps

content/docs/en/sql-review/review-rules/supported-rules.md
This PR only adds the text part. 
Pictures will be added in the next PR.
=> docs: add sql review rules

content/docs/en/concepts/roles-and-permissions.md
Corresponding code change https://github.com/bytebase/bytebase/pull/3173
=> docs: mention Workspace Owner/DBA assume the Project Owner role for all projects

content/docs/en/introduction/use-cases.md, content/docs/en/introduction/what-is-bytebase.md
This PR makes small edits to make our description of tenant database management consistent across different pages.
Part of https://linear.app/bytebase/issue/BYT-1668/tenant-overhaul-related-documentation
=> fix: make our description of tenant db mgmt consistent

locales/en.json, locales/zh.json, pages/sql-review-guide/index.vue
=> chore: update sql review template name

nuxt.config.js, pages/docs/_category/_document.vue, pages/docs/_category/_subcategory/_document.vue, pages/docs/_slug.vue
The 404 error looks like this issue: https://github.com/nuxt/content/issues/346
So we should add docs routes manually instead of auto-generating.
=> fix: add docs related routes

nuxt.config.js
Try to fix 404 error by generating all routes manually instead of using nuxt crawler.
Reference: https://stackoverflow.com/a/73790178
=> chore: disable route crawler

scripts/generateSearchIndex.js
Removing the external `/docs`.
=> fix: docs url in algolia search index

content/blog/sql-review-tool-for-devs.md
=> chore: fix blog tag

content/docs/concepts/roles-and-permissions.md
=> docs: update roles for IM integration

common/type.ts, content/blog/30saas-services-behind-startup.md, content/blog/choose-primary-key-uuid-or-auto-increment.md, content/blog/database-as-code-landscape.md, content/blog/database-as-code.md, content/blog/database-cicd-best-practice-with-github.md, content/blog/database-migration-sqlite-to-postgresql.md, content/blog/database-review-2021-bytebase-chinese.md, content/blog/database-review-2021.md, content/blog/dba-database-developer-decameron.md, content/blog/github-database-cicd-part-1-sql-review-github-actions.md, content/blog/github-database-cicd-part-2-github-database-gitops.md, content/blog/github-database-cicd-part-3-put-them-together.md, content/blog/hacktoberfest-2022.md, content/blog/motherduck-from-sqlite-to-the-docker-for-data.md, content/blog/restoring-a-mysql-database-to-a-point-in-time.md, content/blog/schema-review-policy-mysql.md, content/blog/what-is-database-schema-drift.md
=> docs: add an industry tag to blog and update featured post

content/blog/1-8-0-new-features.md
...so that the blog is shown 💦
=> docs: fix typo

content/docs/_layout.md, content/docs/get-started/work-with-terraform/overview.md
=> chore: add docs for terraform provider

content/docs/get-started/work-with-terraform/overview.md
=> docs: tweak Terraform doc

content/docs/_layout.md, content/docs/tenant-database-management/tenant-gitops.md
This PR adds a new page **Tenant Database Management > Tenant GitOps**.
---
Closes https://linear.app/bytebase/issue/BYT-1759/tenant-yaml-documentation
=> docs: add Tenant GitOps page

pages/pricing/index.vue
| before | after |
| - | - |
| <img width="1258" alt="image" src="https://user-images.githubusercontent.com/24653555/204492877-ba408bce-4c8a-4a03-a1c9-bcc02d5bca27.png"> | <img width="1267" alt="image" src="https://user-images.githubusercontent.com/24653555/204492756-e7770dc6-9780-4b4d-bb15-61ec9c1141b7.png"> |
=> fix: icon style in pricing page

scripts/fetch_config_files.sh
Aggressively retry 3 times for any kind of error.
Otherwise, I have to run `pnpm dev` multiple times to get it online...
=> feat: retry curl

content/docs/administration/webhook-integration/external-approval.md
Update external-approval user doc to reflect changes in https://github.com/bytebase/bytebase/pull/3673
=> docs: update external approval

content/docs/administration/webhook-integration/external-approval.md
Proposed in https://github.com/bytebase/bytebase.com/pull/676#discussion_r1037948207
=> docs: improve external approval wording

content/docs/change-database/synchronize-schema.md
=> docs: update the PostgreSQL sync schema scope

content/docs/_layout.md, content/docs/administration/environment-policy/approval-policy.md, content/docs/concepts/data-model.md, content/docs/concepts/roles-and-permissions.md, content/docs/concepts/schema-change-workflow.md, content/docs/get-started/work-with-a-project/overview.md, content/docs/get-started/work-with-a-project/run-a-ui-workflow.md, content/docs/how-to/workflow/gitops-feature-branch.md, content/docs/sql-review/sql-advisor/gitops-ci.md, content/docs/vcs-integration/enable-version-control-workflow.md, content/docs/vcs-integration/name-and-organize-schema-files.md, content/docs/vcs-integration/overview.md
=> docs: rename version control workflow to gitops workflow

content/docs/_layout.md
to close DVM-351, cc @candy2255 
=> docs: hide state-based migration docs

content/docs/administration/anonymize-data.md
=> docs: notice that anonymize data works only for MySQL

content/docs/how-to/integrations/render.md
=> docs: fix render integration doc

content/docs/_layout.md, content/docs/faq.md, content/docs/introduction/supported-databases.md
=> docs: add supported-databases page

pages/pricing/index.vue
=> chore: update enterprise pricing

common/const.ts, content/docs/how-to/_layout.md, content/docs/how-to/sql-review/postgres-sql-review-guide.md, layouts/content.vue, locales/en.json, locales/zh.json, pages/sql-review-guide/index.vue
=> docs: add PostgreSQL Review Guide

content/docs/administration/webhook-integration/project-webhook.md
add issue stage status change activity to project webhook list
=> feat: add issue stage status change activity to project webhook list

content/blog/database-change-management-with-snowflake-and-github.md, content/blog/database-change-management-with-snowflake.md, content/blog/database-change-management-with-tidb-and-github.md, content/blog/database-change-management-with-tidb.md, content/blog/github-database-cicd-part-2-github-database-gitops.md, content/blog/global-variable-support-in-nuxt.md, content/blog/how-to-configure-database-access-control-and-data-anonymization-for-developer.md, content/blog/how-to-synchronize-database-schemas.md, content/blog/manage-databases-in-bytebase-with-terraform.md, content/docs/disaster-recovery/backup-restore-database/cloud-backup.md, content/docs/get-started/install/deploy-with-docker.md
Also replace hard-coded version string with %%bb_version%% in the blog post
=> docs: add —platform linux/amd64 in docker run command

pages/pricing/index.vue, scripts/fetch_config_files.sh
=> chore: tweak pricing card

content/changelog/bytebase-1-12-0.md
=> docs: update free instance count

content/docs/_layout.md, content/docs/administration/sso/oauth2.md, content/docs/administration/sso/oidc.md, content/docs/administration/sso/overview.md
Examples for Okta and Keycloak will come after.
=> docs: add OIDC docs and examples for Google, GitLab

content/docs/administration/sso/oidc.md, content/docs/administration/sso/overview.md
=> docs: add OIDC guides for Okta and Keycloak

.github/workflows/calibreapp-image-actions.yml
reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
=> fix: schedule cron format

content/docs/get-started/install/deploy-with-docker.md
=> docs: reduce confusion on docker startup guide

common/type.ts, components/Footer.vue, components/Header.vue, content/blog/database-change-management-with-mysql-and-github.md, content/blog/database-change-management-with-mysql.md, content/blog/database-change-management-with-postgresql-and-github.md, content/blog/database-change-management-with-postgresql.md, content/blog/database-change-management-with-snowflake-and-github.md, content/blog/database-change-management-with-snowflake.md, content/blog/database-change-management-with-tidb-and-github.md, content/blog/database-change-management-with-tidb.md, content/blog/database-cicd-best-practice-with-github.md, content/blog/github-database-cicd-part-1-sql-review-github-actions.md, content/blog/github-database-cicd-part-2-github-database-gitops.md, content/blog/github-database-cicd-part-3-put-them-together.md, content/blog/how-to-configure-database-access-control-and-data-anonymization-for-developer.md, content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md, content/blog/how-to-synchronize-database-schemas.md, content/blog/manage-databases-in-bytebase-with-terraform.md, layouts/content.vue, locales/en.json, locales/zh.json, pages/blog/index.vue, pages/database-glossary/index.vue, pages/tutorial/index.vue
* Be more developer centric for self-service.
* Re-order the header link as "Tutorial", "Docs", "Blog", "Pricing".
Fix DVM-422
=> feat: add a tutorial page

components/Header.vue
=> chore: hide live demo in mobile view

content/blog/sql-chat.md
👀 so that there's no shifting right for the article
=> docs: add subtitles and fix title

content/docs/administration/sso/oauth2.md, content/docs/administration/webhook-integration/overview.md, content/docs/get-started/install/external-url.md
=> docs: mention —external-url is required for webhook

components/ActionSectionBottom.vue, components/Header.vue
=> chore: add Self Host button otherwise user may think we only have cloud

content/docs/_layout.md, content/docs/administration/custom-approval.md, content/docs/administration/custom-roles.md
=> docs: add custom roles

content/docs/sql-review/review-rules.md
=> fix: PK key type allowlist supports PostgreSQL
