bytebase/bytebase.com

src/components/pages/blog/aside/aside.tsx, src/components/pages/docs/post-layout/post-layout.tsx, src/components/pages/docs/table-of-contents/table-of-contents.tsx
This pr brings fix for toc
Steps to check:
- open previews [blog post](https://bytebase-git-blog-toc-sticky-bytebase-pixelpoint.vercel.app/blog/bytebase-2-0/), [docs](https://bytebase-git-blog-toc-sticky-bytebase-pixelpoint.vercel.app/docs/introduction/what-is-bytebase/)
- make sure that everything looks and feels as expected
=> fix: toc sticky

content/blog/2023-q1-retrospect.md, src/app/blog/[slug]/page.tsx, src/types/blog-post.ts, src/utils/get-metadata.ts
Fast temporary solution till we'll fix og:image tag for Facebook.
=> fix: temporary remove og-image

src/components/shared/button/button.tsx, src/components/shared/header/header.tsx, src/components/shared/mobile-menu/burger/burger.tsx, src/components/shared/mobile-menu/mobile-menu.tsx, src/svgs/chevron-menu-docs.inline.svg
Updates the design of the main menu after revising the menu items.
How to test:
- open branch preview
- check that all looks good
=> feat: redesign main menu

content/docs/concepts/tenant-database.md
was testing tenant db functions
=> docs: fix broken link

content/blog/migrating-postgres-from-render-to-neon.md
a few (minor) suggestions tehe cc @tianzhou
=> docs: minor changes to migration post

src/lib/api-docs.ts
This pull request brings small fix for path to version file in api-docs.ts file
=> fix: path to version file, resolve algolia index bug

src/app/api/index-to-algolia/route.ts
This pull request brings update for checking webhook headers from vercel to trigger algolia
=> fix: check webhooks auth header

content/docs/_layout.md, content/docs/administration/sso/ldap.md, content/docs/administration/sso/oauth2.md, content/docs/administration/sso/oidc.md, content/docs/administration/sso/overview.md
Part of https://linear.app/bytebase/issue/BYT-3128/support-ldap-in-sso
=> docs: add LDAP configuration guide

content/blog/top-dbeaver-alternative.md
=> docs: fix dbeaver caps

src/app/sql-editor/page.tsx, src/components/pages/sql-editor/hero/hero.tsx, src/components/pages/sql-editor/landing/landing.tsx, src/styles/sql-editor-hero.css
https://github.com/bytebase/bytebase.com/assets/24653555/b0be58e4-543a-40cb-863a-cea97353a8d2
=> chore: add scroll subjects to sql editor landing page

src/app/docs/[...slug]/page.tsx, src/components/pages/blog/aside/aside.tsx, src/components/pages/docs/table-of-contents/table-of-contents.tsx
=> feat: add promo to sticky aside

src/app/[locale]/layout.tsx, src/components/locale-switcher.tsx, src/i18n.ts
=> chore: fix `t` usage

src/components/pages/blog/aside/aside.tsx, src/components/pages/docs/table-of-contents/table-of-contents.tsx
=> chore: fix toc position

src/styles/typography.css
https://github.com/bytebase/bytebase.com/assets/24653555/9c309e7f-e930-48b0-9259-740df88dcc93
Reference: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header
=> chore: update heading offsets

content/blog/saas-services-behind-startup-2023.md
=> docs: fix typo

content/docs/get-started/self-host.md
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
=> chore: specify replicas as 1 explicitly

src/app/[locale]/layout.tsx
Reference: https://github.com/vercel/next.js/discussions/35773#discussioncomment-3603586
=> chore: dynamic import client components

content/docs/get-started/self-host.md
- Use StatefulSet instead of Deployment.
- Add ingress configuration.
=> chore: improve k8s installation

src/app/[locale]/docs/[...slug]/page.tsx, src/components/pages/blog/aside/aside.tsx, src/components/pages/docs/table-of-contents/table-of-contents.tsx
Close https://github.com/bytebase/bytebase.com/issues/283
=> fix: toc height and autoscroll behavior

src/components/pages/docs/table-of-contents/table-of-contents.tsx, src/components/pages/sql-review-guide/content/content.tsx, src/components/pages/sql-review-guide/mobile-sidebar/mobile-sidebar.tsx, src/components/pages/sql-review-guide/sidebar/sidebar.tsx
https://github.com/bytebase/bytebase.com/assets/24653555/78834b87-568f-48a6-a54a-4e9837aebd80
=> chore: add offset styles to archor element

src/components/shared/content/content.tsx
Close DVM-733
https://github.com/bytebase/bytebase.com/assets/24653555/17383f97-dd06-441d-941e-e36285e534ee
=> chore: add ahref to headings

src/components/pages/pricing/table/data/calculate-cell-height.ts, src/components/pages/pricing/table/plan-card/feature-list/feature-list.tsx, src/components/pages/pricing/table/plan-card/plan-card.tsx, src/components/pages/pricing/table/table.tsx, src/components/shared/header/header.tsx
Close BYT-5733
https://github.com/bytebase/bytebase.com/assets/24653555/9dd1c54d-4dc6-4624-938e-18c74c6f47e5
=> chore: update plan card styles on sticky

data/sql-review/sql-review-schema.yaml, data/sql-review/sql-review.dev.yaml, data/sql-review/sql-review.prod.yaml, src/lib/api-sql-review.ts, src/scripts/fetch-sql-review.mjs, src/types/sql-review.ts
We changed the YAML and flatten the rules by engine. Related PR https://github.com/bytebase/bytebase/pull/12623
=> fix: sql review yaml changed

content/blog/neon-vs-supabase.md
updates language around Supabase's postgres compatibility (see: https://github.com/supabase/postgres), and adds Hipaa compliance a la https://supabase.com/security
=> chore: supabase edits

src/app/[locale]/sql-editor/page.tsx, src/components/pages/sql-editor/hero/hero.tsx, src/styles/sql-editor-hero.css
https://github.com/user-attachments/assets/11177824-16e9-473b-9947-84980e6a094d
=> chore: add datagrip subject to sql editor page

content/docs/vcs-integration/create-migration-files.md
There is  the link to localhost path.
Fixing the link path
=> docs: fix link

data/locales/sql-review/en.json
refer to https://github.com/bytebase/bytebase/pull/14196
=> chore: sync locale file of sql review rules

content/docs/tutorials/database-change-management-with-jira-automated.md, content/docs/tutorials/database-change-management-with-jira-manual.md
add what is bytebase in case the article is posted in other site
=> docs: update jira tuts

src/components/pages/pricing/hero/hero.tsx
=> chore: pricing v4

src/components/pages/about/hero/hero.tsx, src/components/pages/batch-change/hero/hero.tsx, src/components/pages/blog/blog-post-hero/blog-post-hero.tsx, src/components/pages/branching/hero/hero.tsx, src/components/pages/changelog/hero/hero.tsx, src/components/pages/data-masking/hero/hero.tsx, src/components/pages/schema-migration/hero/hero.tsx, src/components/pages/sql-editor/hero/hero.tsx
=> chore: reduce padding top in mobile view

src/components/pages/changelog/posts-list/posts-list.tsx
=> chore: add read more in changelogs

src/app/[locale]/page.tsx, src/components/pages/home/hero-v1/db-scheme.tsx, src/components/pages/home/hero-v1/hero-v1.tsx, src/components/pages/home/hero-v1/index.ts, src/components/pages/home/promo-cards/card/card.tsx, src/components/pages/home/promo-cards/card/index.ts, src/components/pages/home/promo-cards/index.ts, src/components/pages/home/promo-cards/promo-cards.tsx
https://github.com/user-attachments/assets/c704003e-ebec-488a-b99b-225730e64c6c
=> chore: tweak home hero

src/components/pages/home/hero/hero.tsx, src/components/pages/pricing/hero/card/card.tsx
=> chore: tweak text style

content/docs/change-database/rollback-data-changes.md
=> docs: update mssql backup version

content/docs/change-database/rollback-data-changes.md
=> docs: remove classic experience for backup

content/docs/tutorials/database-change-management-with-jira-automated.md
do a quick fix first, code fix can be fixed later
=> doc: quick fix

content/docs/administration/sso/oidc.md
=> docs: add group syncing from OIDC

content/docs/_layout.md, content/docs/vcs-integration/azure-devops.md, content/docs/vcs-integration/bitbucket.md, content/docs/vcs-integration/github.md, content/docs/vcs-integration/gitlab.md, content/docs/vcs-integration/overview.md
See what integrations Bytebase supports immediately.
=> feat: gitops integrations

src/components/pages/docs/mobile-sidebar/mobile-sidebar.tsx, src/components/pages/pricing/table/table.tsx
=> fix: sticky top of pricing feature table

mintlify/tutorials/gitops-azure-devops-workflow.mdx
=> docs: update gitops azure devops workflow

mintlify/vcs-integration/overview.mdx
=> docs: gitops filename requirement section
