bytebase/bytebase.com

pages/database-glossary/index.vue
I tried to suggest some changes on the [Database Glossary page](https://bytebase.com/database-glossary) and found the suggestion URL invalid. I checked the commit history for bytebase.com/pages/database-glossary, and according to the PR ["Move to database-glossary sub folder"](https://github.com/bytebase/bytebase.com/commit/5a5382322f3b7f286acf2bac7fb82b960ac7dee0#diff-20abb46be334ff13b26d2358db5a806b6cc99c118ead6d52adf2e99ce4532b88) I identified the valid URL.
=> glossary: fix the suggestion URL which turned invalid after file reorg

pages/refund/index.vue
Add /refund page
Where shall we put this link, seems should at least add one in /pricing page?
=> feat: add refund page

components/DocsSidebar.vue, components/DocumentViewer.vue, docs/concepts/overview.md, docs/document-write-guide.md, docs/features/overview.md, docs/install/overview.md, docs/operating/overview.md, docs/reference/overview.md, docs/settings/overview.md, docs/use-bytebase/overview.md, docs/what-is-bytebase.md, nuxt.config.js, pages/docs/_category/_document.vue, pages/docs/_category/_subcategory/_document.vue, pages/docs/_slug.vue
* Add `hide` field to make doc unclickable into `.md` fields;
* Add `description` field to dynamic generate page metadata. And it's optional right now(I just write two example description for "/docs/what-is-bytebase" and "/docs/document-write-guide", maybe @bytebase/bytebase-devrel could help finish this). If it is null, this field would be a slice string of document content.
=> feat: overview page unclickable

nuxt.config.js
We are going to hide non-chinese post which is only searchable by the search engine
=> docs: Use “Hidden” instead of “Chinese” tag to hide post

components/TheHeader.vue
Fix width overflow issue caused by the crowded buttons in mobile view.
=> fix: header styles in mobile view

components/DocumentViewer.vue, components/IncludeBlock.vue, types/docs.d.ts
New atom component `IncludeBlock` for rendering other markdowns directly. Usage:
```markdown
...
<include-block url="features/archive"></include-block>
Bytebase is a database schema change and version control management tool for teams.
...
```
=> feat: include-block

components/DocsSidebar.vue, layouts/content.vue
Strange bug:
When clicking a `nuxt-link` from `/` to `/docs/xxx` page, the `$content` in `useAsync` would not works properly.
Solution:
Get docs data in `onMount` hook and add a loading status for sidebar.
=> fix: fetch docs data in sidebar

components/DocsSidebar.vue, components/DocumentViewer.vue, docs/en/_layout.md, nuxt.config.js, package.json, pnpm-lock.yaml
* use `useFetch` to pre-fetch content data, this makes doc pages can get all data in the build; (related PR #126) 
* add a valid category logic for the next requirement "/docs/cli";
=> feat: enable submenu for docs

common/const.ts, docs/en/concepts/overview.md, docs/en/features/overview.md, docs/en/install/overview.md, docs/en/operating/overview.md, docs/en/reference/overview.md, docs/en/settings/overview.md, docs/en/troubleshooting/overview.md, docs/en/use-bytebase/overview.md
We no longer need these empty `overview.md`.
=> chore: remove useless overview docs

nuxt.config.js, package.json, pnpm-lock.yaml
As the vercel docs says that we don't need to add this plugin manually, but it's still in the ready status. Let's add it manually for testing.
https://vercel.com/docs/concepts/analytics#nuxt.js-(v2+)
=> chore: add `@nuxtjs/web-vitals` to enable vercel analytics

package.json, pnpm-lock.yaml
Fix the build error in Vercel:
Maybe caused by `pnpm v7`: https://github.com/pnpm/pnpm/issues/4684
As the maintainer says, we need to install **the missing peer dependencies**.
=> chore: fix missing package

content/docs/en/_layout.md
the emoji for intro seems missing
=> docs: add back the missing emoji for intro and expand get started by default

content/docs/en/install/build-from-source.md, content/docs/en/install/install-script.md
Reduce the workload to change version string during upgrade
=> docs: remove the unnecessary place to mention explicit version number

components/DocumentViewer.vue, components/Toc.vue, layouts/blog.vue, layouts/default.vue, pages/blog/_slug/index.vue, pages/changelog/_slug/index.vue, pages/changelog/index.vue, tailwind.config.js
1. Override some default style provided by [@tailwindcss/typography](https://tailwindcss.com/docs/typography-plugin).
- Remove rounding backticks of inline code and improve its style.
| before | after |
|:--:|:--:|
| ![image](https://user-images.githubusercontent.com/56376387/175248529-e17aa952-b75c-45dc-878f-f5f7cf5c2c47.png) | ![image](https://user-images.githubusercontent.com/56376387/175249334-a82625c4-94ce-457e-adcc-711aec7a8a7a.png) |
- Center images and fill the horizontal space.
| before | after |
|:--:|:--:|
| ![image](https://user-images.githubusercontent.com/56376387/175249785-d472e181-4538-46d4-85ea-d4df80a88e57.png) | ![image](https://user-images.githubusercontent.com/56376387/175249943-a3c5d7e8-8cc8-4e52-b0b7-86b4ed7d372d.png) |
2. Add table of contents to blog/changelog …
=> feat: improve blog and changelog's rendering mechanism

components/TeamSection.vue
=> docs: adjust founder section padding to align text

common/teammate.ts
They are the author of the blog post so we can't remove them
=> docs: add back tianzhou & danny otherwise it will break blog

layouts/content.vue
Hide other(blog/changelog/pricing) entry temporarily to fix the broken docs header in mobile.
|before|after|
|-|-|
|<img width="440" alt="image" src="https://user-images.githubusercontent.com/24653555/177064168-60e3d270-dc78-4905-94ad-5a321de40278.png">|<img width="432" alt="image" src="https://user-images.githubusercontent.com/24653555/177064184-628cf91a-51e4-426d-bf96-8a0fe172990f.png">|
=> fix: docs header style in mobile

components/global/Version.vue, content/docs/en/get-started/deploy-to-production/deploy-with-docker.md, content/docs/en/get-started/deploy-to-production/installation-script.md, content/docs/en/get-started/quick-start.md
Added a global version component which contains the latest version number. Now we just need to change one place after we publish a new version.
After some investigation, I found out that a [MarkDoc-like](https://markdoc.io/docs/variables) **variable** is not supported in Nuxt Content currently: https://github.com/nuxt/content/issues/997#issuecomment-1005507397.
So I'm actually using a **component** here. A `Version` component may not be an elegant way to achieve this, but it works.
=> feat: add a global version component

nuxt.config.js
Remove sitemap route which startWith `["/zh/docs", "/zh/changelog", "/zh/blog"]`.
=> chore: remove unwanted route for sitemap

common/const.ts, components/DocsSidebar.vue, components/DocumentViewer.vue
For example, the breadcrumb for `Configure External PostgreSQL` will be `🐣 Get Started / Install / Configure External PostgreSQL`, and `🐣 Get Started` isn't a link.
=> chore: add breadcrumb to docs

pages/changelog/_slug/index.vue, pages/changelog/index.vue
Style changes only on **changelog** images:
- Added box-shadow.
- Preserve the original width of images.
| Before | After |
| :---: | :---: |
| <img width="1454" alt="CleanShot 2022-08-02 at 15 09 11@2x" src="https://user-images.githubusercontent.com/56376387/182313726-9aae31c0-4e08-4553-bcdf-000b3e2272ce.png"> | <img width="1453" alt="CleanShot 2022-08-02 at 15 09 40@2x" src="https://user-images.githubusercontent.com/56376387/182313814-25c160cc-561b-4078-84f3-37a133c3cb10.png"> |
=> style: apply shadow and width changes to changelog images

pages/demo/index.vue
Fix: https://www.bytebase.com/zh/demo click on *视频演示* not working.
=> fix: demo entry page cannot get to demo videos

components/global/Version.vue, content/docs/en/get-started/install/deploy-to-kubernetes.md, content/docs/en/get-started/install/deploy-with-docker.md, content/docs/en/get-started/install/overview.md, content/docs/en/get-started/quick-start.md, nuxt.config.js, package.json, plugin/vue-gtag.ts, pnpm-lock.yaml
Use a more elegant way to inject the latest version. Also, this brings back the missing `copy` button in code blocks.
=> refactor: inject bb_version before content parse

locales/en.json, locales/zh.json, pages/about.vue
The rendering is strange with underscored comma on Mac.
=> chore: improve rendering

locales/zh.json, pages/index.vue
* Avoid text overlapping with the illustration
* Make Chinese 4 lines to look nicer
=> docs: improve 1st screen

components/DocLinkBlock.vue, components/HintBlock.vue, package.json, pages/refund/index.vue, pnpm-lock.yaml
Upgrade lockfile version to `5.4`, same as `bytebase/bytebase`.
=> chore: regenerate pnpm lock file

content/docs/en/_layout.md
"Multi-tenancy" means completely different things from what Bytebase provides based on common sense[^1] and our `o/devterm`:
> Multitenancy is a reference to the mode of operation of software where multiple independent instances of one or multiple applications operate in a shared environment.
[^1]: https://www.gartner.com/en/information-technology/glossary/multitenancy
=> chore: rename tenant page title

pages/index.vue
Reference: [pointer events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)
=> fix: use `pointer-events-none` instead of `z-index` to illustration cover

components/SchemaSystem/SchemaConfigurationPage.vue, locales/en.json, locales/zh.json
As the issue https://linear.app/bytebase/issue/DVM-253/expose-sql-review-action-and-github-app-more-explicitly-in-sql-review said, we should expose the SQL Review GitHub App in SQL Review Guide page.
Sadly I haven’t found a better solution to expose this, so just simply add a sentence below the download button.
=> chore: expose the sql review github app

content/docs/_layout.md, content/docs/concepts/tenant-database.md, content/docs/introduction/use-cases.md, content/docs/introduction/what-is-bytebase.md, content/docs/tenant-database-management/overview.md, content/docs/tenant-database-management/tenant-project.md, pages/index.vue
This PR breaks down the single-page Tenant Database Management into a directory of pages. This is a first one of a series of PRs, put up these changes because I want to decouple the documentation of the YAML file support from tenant doc overhaul (which takes much longer), so the former can be added as a sub-page in the directory without causing merge conflicts.
---
Part of https://linear.app/bytebase/issue/BYT-1668/tenant-overhaul-related-documentation
=> docs: restructure tenant database management pages

content/docs/administration/webhook-integration/external-approval.md
Add a warning because the scope "approval:approval:readonly" is often omitted by users.
=> docs: add warning

content/docs/concepts/roles-and-permissions.md, nuxt.config.js, pages/index.vue
* Title from "Bytebase | Database DevOps" to "Database CI/CD | Database DevOps | Bytebase", put features first
* Remove "View all instances" from Workspace Developer permission. Developer doesn't care instance, they only care databases.
=> docs: update website title and remove View all Instance permission for developer

content/docs/how-to/integrations/supabase.md
Supabase team says they will "grant supabase_functions_admin to postgres;" when installing the extension. So remove the note here.
=> docs: remove the postgres role note for Supabase

content/docs/_layout.md, content/docs/get-started/configure-workspace/configure-with-terraform.md, content/docs/get-started/terraform.md
We're using terraform to configure workspace-level environment/instance/role. So the doc would better belong to 'Configure  Workspace' Section.
=> docs: move terraform to configure part

content/docs/get-started/install/external-postgres.md
Update the minimum PostgreSQL version in prerequisites to 14.
Because we want to use the jsonb subscription function. https://www.postgresql.org/docs/14/datatype-json.html#JSONB-SUBSCRIPTING
=> docs: update postgres version

components/BookDemoSection.vue, components/SubscribeSection.vue, pages/demo/index.vue, plugin/segment.ts
Issue https://linear.app/bytebase/issue/BYT-2401/clicking-the-try-now-button-in-team-plan-would-trigger-2-requests-for
The true problem is, the login/sign up in the hub will trigger a "New request for live demo" message to the Lark.
1. We will send new users in the hub to the newsletter. Issue https://linear.app/bytebase/issue/DVM-372/mailchimp-audience
2. Demo request workflow: Click the button -> Send metric to Segment -> Integrate with MailChimp -> Post webhook to Zapier -> Post webhook to Lark
As our newsletter in MailChimp has the Zapier integration, all updates in the newsletter will be sent to the Zapier, then send the "New request for live demo" message to the Lark.
So,
1. Fix the Segment identify func, and ensure we have posted the `category` field to the MailChimp.
2. Update the …
=> fix: mailchimp integration

scripts/fetch_config_files.sh
Need to change the upstream URL as we changed the folder in bytebase. We can revert the version from `main` to `cat ./VERSION` after 1.12.0 is released.
=> chore: update script

content/docs/api/sql-advise.md
- Remove duplicate white space before colon.
- Use code font to mark up query parameters in the endpoint.
- Use sentence case for H3
=> docs: fix the format in sql-advise

README.md
In https://github.com/bytebase/bytebase/pull/2032, [`frontend/src/types/sql-review-schema.yaml`](https://github.com/bytebase/bytebase/blob/main/frontend/src/types/sql-review-schema.yaml) is removed and [`frontend/src/types/sql-review-schema.yaml`](https://github.com/bytebase/bytebase/blob/main/frontend/src/types/sql-review-schema.yaml) is introduced. But the link is not updated in README.
This PR replaces a broken link of rule configuration file with `frontend/src/types/sql-review-schema.yaml`.
=> docs: fix a broken link in README

content/docs/_layout.md, content/docs/change-database/rollback-data-changes.md, content/docs/introduction/supported-databases.md
The contents may change as the feature is still WIP.
Completing BYT-2508
=> docs: add rollback data changes

components/ActionSectionBottom.vue, components/LogoCloudSection.vue
=> chore: update logo and action section mobile style

content/blog/database-change-management-with-amazon-aurora-and-github.md, content/blog/database-change-management-with-clickhouse-and-github.md, content/blog/database-change-management-with-mysql-and-github.md, content/blog/database-change-management-with-postgresql-and-github.md, content/blog/database-change-management-with-snowflake-and-github.md, content/blog/database-change-management-with-tidb-and-github.md, content/blog/database-cicd-best-practice.md, content/blog/github-database-cicd-part-2-github-database-gitops.md, content/blog/github-database-cicd-part-3-put-them-together.md, content/docs/vcs-integration/enable-gitops-workflow.md, content/docs/vcs-integration/name-and-organize-schema-files.md, content/docs/vcs-integration/tenant-gitops.md
TODO: need Adela's help to update blog pictures.
=> chore: replace environment name with environment id in GitOps path

components/ActionSection.vue, components/ActionSectionBottom.vue, components/Header.vue, components/Icons/Cloud.vue, layouts/content.vue, locales/en.json, locales/zh.json
Close BYT-2777
DO NOT merge this PR till the hub is released
=> chore: update for saas

components/Header.vue, layouts/content.vue
This is a followup of https://github.com/bytebase/bytebase/pull/5150 and https://github.com/bytebase/bytebase.com/pull/847
With this change, the user journey is: 
* Sign up for Cloud
* Live demo -> self-host / sign up for cloud
So we still expose the live demo to the user.
=> chore: use Live demo button in the header

components/ActionSection.vue, components/ActionSectionBottom.vue, components/Header.vue, layouts/content.vue
=> fix: redirect page

pages/demo-confirm.vue
This is a callback page that we can track for Google ads after user books a demo.
=> docs: add a demo-confirm page

pages/blog/_slug/index.vue
=> chore: fix css integraiton icon in safari

pages/pricing/index.vue
the mailto: experience is not inferior as it brings a local default client (user may not have configured one).
Using google form instead, and we will receive webhook event on each request.
We will improve this further after the new website, but good for now.
=> chore: redirect contact enterprise to google form

content/docs/get-started/install/deploy-to-sealos.md
To keep consistent with deploy in kubernetes.
=> docs: using PG_URL in env instead of args

content/docs/administration/sso/oidc.md
=> docs: add casdoor docs

content/docs/introduction/supported-databases.md
cc @Candybase @d-bytebase @whhe
=> docs: add ob support
